Q] Perform the following operations using R/Python on suitable data sets:

a) read data from different formats (like csv, xls)
b) indexing and selecting data, sort data,  
c) describe attributes of data, checking data types of each column,  
d) counting unique values of data, format of each column, converting variable data type (e.g.
from long to short, vice versa),  
e) identifying missing values and fill in the missing values

In [ ]:
#importing all requared libraries
import pandas as pd

In [ ]:
#reading data from .xlsx
#salary=pd.read_excel("")
#reading data from csv file
salary=pd.read_csv("/jobs_in_data.csv")

In [ ]:
salary.head()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M

In [ ]:
#indexing and selecting data, sort data
#indexing
#salary["job_category"]
#selecting
#salary.iloc[2:4,1:6]
#sort data
salary.sort_values("salary")

In [ ]:
#describe attributes of data,checking data types of each column
types=salary.dtypes
print(types)

work_year              int64
job_title             object
job_category          object
salary_currency       object
salary                 int64
salary_in_usd          int64
employee_residence    object
experience_level      object
employment_type       object
work_setting          object
company_location      object
company_size          object
dtype: object

In [ ]:
#counting unique values of data,format of each column,converting variable data type(long to short)
uni=salary.salary_in_usd.nunique()
print(uni)

1786

In [ ]:
#identifying missing values and fill in the missing values
salary.isnull()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9350,False,False,False,False,False,False,False,False,False,False,False,False
9351,False,False,False,False,False,False,False,False,False,False,False,False
9352,False,False,False,False,False,False,False,False,False,False,False,False
9353,False,False,False,False,False,False,False,False,False,False,False,False
9354,False,False,False,False,False,False,False,False,False,False,False,False